#!/usr/bin/env bun

import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { format } from 'prettier';
import ts from 'typescript';

const display = (parts: ts.SymbolDisplayPart[] | undefined): string =>
  ts.displayPartsToString(parts).trim();

const targetSymbol = (checker: ts.TypeChecker, symbol: ts.Symbol): ts.Symbol =>
  symbol.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(symbol) : symbol;

function declarationText(checker: ts.TypeChecker, symbol: ts.Symbol): string {
  const target = targetSymbol(checker, symbol);
  const declaration = target.valueDeclaration ?? target.declarations?.[0];
  assert.ok(declaration, `Public export ${symbol.name} has no declaration.`);
  if (
    ts.isInterfaceDeclaration(declaration) ||
    ts.isTypeAliasDeclaration(declaration) ||
    ts.isEnumDeclaration(declaration)
  ) {
    return declaration
      .getText()
      .replace(/^export\s+/, '')
      .replace(/^declare\s+/, '');
  }
  const type = checker.getTypeOfSymbolAtLocation(target, declaration);
  return `const ${symbol.name}: ${checker.typeToString(
    type,
    declaration,
    ts.TypeFormatFlags.NoTruncation | ts.TypeFormatFlags.UseAliasDefinedOutsideCurrentScope,
  )};`;
}

function renderTag(tag: ts.JSDocTagInfo): string | undefined {
  const value = display(tag.text);
  if (!value) return undefined;
  if (tag.name === 'returns' || tag.name === 'return') return `**Returns:** ${value}`;
  if (tag.name === 'throws' || tag.name === 'throw') return `**Throws:** ${value}`;
  if (tag.name === 'param') {
    const [name = '', ...description] = value.split(/\s+-?\s*/);
    return `- **${name}:** ${description.join(' ').trim()}`;
  }
  return `**${tag.name}:** ${value}`;
}

function renderSymbol(checker: ts.TypeChecker, symbol: ts.Symbol): string {
  const target = targetSymbol(checker, symbol);
  const documentation = display(target.getDocumentationComment(checker));
  assert.ok(documentation, `Public export ${symbol.name} needs a documentation comment.`);
  const tags = target
    .getJsDocTags(checker)
    .map(renderTag)
    .filter((tag) => tag !== undefined);
  return [
    `### \`${symbol.name}\``,
    '',
    documentation,
    '',
    '```ts',
    declarationText(checker, symbol),
    '```',
    ...(tags.length ? ['', ...tags.flatMap((tag) => [tag, ''])] : []),
  ].join('\n');
}

async function generateApiDocumentation(root: string): Promise<string> {
  const configFile = ts.readConfigFile(path.join(root, 'tsconfig.json'), ts.sys.readFile);
  if (configFile.error)
    throw new Error(ts.flattenDiagnosticMessageText(configFile.error.messageText, '\n'));
  const config = ts.parseJsonConfigFileContent(configFile.config, ts.sys, root);
  const program = ts.createProgram(config.fileNames, config.options);
  const checker = program.getTypeChecker();
  const source = program.getSourceFile(path.join(root, 'lib/index.ts'));
  assert.ok(source, 'Missing public API source lib/index.ts.');
  const moduleSymbol = checker.getSymbolAtLocation(source);
  assert.ok(moduleSymbol, 'Missing module symbol for lib/index.ts.');
  const symbols = checker
    .getExportsOfModule(moduleSymbol)
    .filter(({ name }) => name !== 'default' && name !== 'module.exports')
    .sort((left, right) => left.name.localeCompare(right.name));
  const values = symbols.filter(
    (symbol) => targetSymbol(checker, symbol).flags & ts.SymbolFlags.Value,
  );
  const types = symbols.filter(
    (symbol) => !(targetSymbol(checker, symbol).flags & ts.SymbolFlags.Value),
  );
  const markdown = [
    '# API',
    '',
    '<!-- Generated by `bun run docs:api`. Edit public TypeScript docblocks or the generator, not this file. -->',
    '',
    'This reference covers every supported export from `@tanaab/codex-tools`. Start with the',
    '[README](./README.md) for installation or the [CLI guide](./CLI.md) for terminal usage.',
    '',
    'Imports through `lib/`, `utils/`, `scripts/`, or `dist/` are private and unsupported.',
    '',
    '## Usage',
    '',
    '<!-- codex-tools-example:api -->',
    '',
    '```ts',
    "import { runOperation, type CodexToolsOptions } from '@tanaab/codex-tools';",
    '',
    'const options: CodexToolsOptions = {',
    "  repoRoot: '/path/to/plugin',",
    "  codexHome: '/path/to/codex-home',",
    '};',
    "const result = await runOperation('status', options);",
    '',
    'if (!result.ok) console.error(result.issue);',
    '```',
    '',
    '## Functions',
    '',
    ...values.flatMap((symbol) => [renderSymbol(checker, symbol), '']),
    '## Types',
    '',
    ...types.flatMap((symbol) => [renderSymbol(checker, symbol), '']),
  ];
  return format(
    markdown
      .join('\n')
      .replace(/\n{3,}/g, '\n\n')
      .trimEnd() + '\n',
    {
      parser: 'markdown',
      printWidth: 100,
      proseWrap: 'preserve',
      embeddedLanguageFormatting: 'auto',
      singleQuote: true,
    },
  );
}

const args = process.argv.slice(2);
if (args.some((arg) => arg !== '--check')) throw new Error('Usage: docs:api [--check]');
const root = fileURLToPath(new URL('..', import.meta.url));
const destination = path.join(root, 'API.md');
const generated = await generateApiDocumentation(root);
if (args.includes('--check')) {
  assert.equal(
    (await readFile(destination, 'utf8')).replaceAll('\r\n', '\n'),
    generated.replaceAll('\r\n', '\n'),
    'API.md is stale. Run `bun run docs:api` and commit the result.',
  );
} else {
  await writeFile(destination, generated);
}
